name: Deploy GoFunction Test Site to AWS S3 Cloudfront
on:
  push:
    branches:
      - develop
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      content: read
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          #aws-access-key-id: AKIAYQFDFO25HQNLVQY5
          #aws-secret-access-key: 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
          role-to-assume: arn:aws:iam::584457746106:role/mynewrole
          aws-region: us-east-1
      - name: Copy files to the test website
        run: |
          aws s3 sync . s3://martinying-develop-2
      - name: Create CloudFront Invalidation for the test website
        run: |
          aws cloudfront create-invalidation --distribution-id E1MS8ZKXIRP98C --paths "/*"