name: Deploy GoFunction Test Site to AWS S3 Cloudfront
on:
  push:
    branches:
      - develop
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    environment: develop
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v1

      - name: Echo
        run: |
          echo ${GITHUB_REF##*/}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{secrets.AWS_ROLE_TO_ASSUME}}
          aws-region: ${{secrets.AWS_DEFAULT_REGION}}
      - name: Copy files to the test website
        run: |
          aws s3 sync . s3://${{secrets.S3_BUCKET}}
      - name: Create CloudFront Invalidation for the test website
        run: |
          aws cloudfront create-invalidation --distribution-id ${{secrets.CLOUDFRONT_DISTRIBUTION_ID}} --paths "/*"